service: dmoney-serverless-boilerplate

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    # Create your env file and add it to .gitignore
    # environment: ${file(./.env.json)}

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: main
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
    printOutput: true
    location: './bin/'

